from collections.abc import Callable, MutableMapping
from typing import Any, Self, TypeAlias, TypeVar

__all__ = ["BaseModel", "ConfigDict", "Field", "ValidationError", "field_validator"]

ConfigDict: TypeAlias = dict[str, Any]

class ValidationError(Exception): ...

class BaseModel:
    def __init__(self, **data: object) -> None: ...
    def dict(
        self, *, by_alias: bool = ..., exclude_none: bool = ...
    ) -> MutableMapping[str, object]: ...
    def model_dump(self) -> dict[str, object]: ...
    @classmethod
    def model_validate(cls, obj: object) -> Self: ...
    def __getattr__(self, name: str) -> object: ...

_T = TypeVar("_T")
_ModelT = TypeVar("_ModelT", bound=BaseModel)

def Field(*args: object, **kwargs: object) -> Any: ...
def field_validator(
    *fields: str, mode: str | None = ...
) -> Callable[[Callable[..., _T]], Callable[..., _T]]: ...
