
__all__ = [
    "QColor",
    "QFont",
    "QPainter",
    "QPixmap",
    "QTextCursor",
]

class QColor:
    def __init__(self, value: str) -> None: ...

class QFont:
    def setUnderline(self, value: bool) -> None: ...

class QPainter:
    class RenderHint(int):
        Antialiasing: QPainter.RenderHint

    Antialiasing: int

    def __init__(self, device: object | None = ...) -> None: ...
    def begin(self, device: object) -> bool: ...
    def end(self) -> None: ...
    def setRenderHint(self, hint: int, on: bool = ...) -> None: ...
    def setPen(self, pen: object) -> None: ...
    def setBrush(self, brush: object) -> None: ...
    def drawText(self, rect: object, flags: int, text: str) -> None: ...
    def fillRect(self, rect: object, color: QColor | object) -> None: ...

class QPixmap:
    def __init__(self, path: str | None = ...) -> None: ...
    def isNull(self) -> bool: ...
    def scaled(
        self,
        width_or_size: float | object,
        height: int | None = ...,
        aspectMode: int | None = ...,
        transformMode: int | None = ...,
    ) -> QPixmap: ...

class QTextCursor:
    End: int

    def movePosition(self, operation: int) -> None: ...
