from collections.abc import Iterable, Sequence
from typing import overload

from .QtCore import QObject, QPoint, QSize, Signal
from .QtGui import QPixmap

__all__ = [
    "QAbstractItemView",
    "QAction",
    "QApplication",
    "QCheckBox",
    "QComboBox",
    "QDialog",
    "QDialogButtonBox",
    "QDoubleSpinBox",
    "QFileDialog",
    "QFormLayout",
    "QFrame",
    "QGraphicsItem",
    "QGraphicsScene",
    "QGraphicsView",
    "QGridLayout",
    "QGroupBox",
    "QHBoxLayout",
    "QHeaderView",
    "QInputDialog",
    "QLabel",
    "QLayout",
    "QLineEdit",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMenu",
    "QMessageBox",
    "QPlainTextEdit",
    "QPushButton",
    "QScrollArea",
    "QSizePolicy",
    "QSlider",
    "QSpinBox",
    "QSplitter",
    "QStackedWidget",
    "QStatusBar",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QVBoxLayout",
    "QWidget",
]

class QGraphicsItem(QObject):
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def boundingRect(self) -> object: ...
    def setToolTip(self, text: str) -> None: ...

class QFont:
    def pointSize(self) -> int: ...
    def setPointSize(self, size: int) -> None: ...
    def setBold(self, bold: bool) -> None: ...

class QAction(QObject):
    triggered: Signal

    def __init__(self, text: str = ..., parent: QObject | None = ...) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setData(self, data: object) -> None: ...
    def data(self) -> object: ...

class QLayout(QObject):
    def addWidget(
        self, widget: QWidget, stretch: int = ..., alignment: int = ...
    ) -> None: ...
    def addLayout(self, layout: QLayout) -> None: ...
    def addStretch(self, stretch: int = ...) -> None: ...
    def addSpacing(self, size: int) -> None: ...
    def indexOf(self, widget: QWidget) -> int: ...
    def setStretch(self, index: int, stretch: int) -> None: ...
    def setContentsMargins(
        self, left: int, top: int, right: int, bottom: int
    ) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...

class QHBoxLayout(QLayout):
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def setContentsMargins(
        self, left: int, top: int, right: int, bottom: int
    ) -> None: ...

class QVBoxLayout(QLayout):
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def setContentsMargins(
        self, left: int, top: int, right: int, bottom: int
    ) -> None: ...

class QGridLayout(QLayout):
    def __init__(self, parent: QObject | None = ...) -> None: ...
    @overload
    def addWidget(
        self,
        widget: QWidget,
        stretch: int = ...,
        alignment: int = ...,
    ) -> None: ...
    @overload
    def addWidget(
        self,
        widget: QWidget,
        row: int,
        column: int,
        row_span: int = ...,
        column_span: int = ...,
        alignment: int = ...,
    ) -> None: ...
    @overload
    def addLayout(
        self,
        layout: QLayout,
    ) -> None: ...
    @overload
    def addLayout(
        self,
        layout: QLayout,
        row: int,
        column: int,
        row_span: int = ...,
        column_span: int = ...,
        alignment: int = ...,
    ) -> None: ...
    def setContentsMargins(
        self, left: int, top: int, right: int, bottom: int
    ) -> None: ...
    def setHorizontalSpacing(self, spacing: int) -> None: ...
    def setVerticalSpacing(self, spacing: int) -> None: ...
    def setColumnStretch(self, column: int, stretch: int) -> None: ...

class QSizePolicy:
    class Policy(int):
        Fixed: QSizePolicy.Policy
        Preferred: QSizePolicy.Policy
        Expanding: QSizePolicy.Policy

    def __init__(self, horizontal: int = ..., vertical: int = ...) -> None: ...

class QFormLayout(QLayout):
    class FieldGrowthPolicy:
        ExpandingFieldsGrow: int

    def __init__(self, parent: QObject | None = ...) -> None: ...
    def addRow(self, label: str | QWidget, field: QWidget | QLayout) -> None: ...
    def setFieldGrowthPolicy(self, policy: int) -> None: ...

class QWidget(QObject):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setObjectName(self, name: str) -> None: ...
    def setLayout(self, layout: QLayout) -> None: ...
    def layout(self) -> QLayout | None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setFixedHeight(self, height: int) -> None: ...
    def setFixedWidth(self, width: int) -> None: ...
    def setFixedSize(self, width: int, height: int) -> None: ...
    def setMinimumHeight(self, height: int) -> None: ...
    def setMinimumWidth(self, width: int) -> None: ...
    def setMinimumSize(self, width: int, height: int) -> None: ...
    def setMaximumHeight(self, height: int) -> None: ...
    def setMaximumWidth(self, width: int) -> None: ...
    def setSizePolicy(
        self, horizontal: int | QSizePolicy, vertical: int | QSizePolicy | None = ...
    ) -> None: ...
    def sizePolicy(self) -> QSizePolicy: ...
    def size(self) -> QSize: ...
    def font(self) -> QFont: ...
    def setFont(self, font: QFont) -> None: ...
    def setContextMenuPolicy(self, policy: int) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def resizeEvent(self, event: object) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def mapToGlobal(self, point: QPoint) -> QPoint: ...
    def show(self) -> None: ...
    def close(self) -> None: ...
    def closeEvent(self, event: object) -> None: ...

class QGroupBox(QWidget):
    def __init__(self, title: str = ..., parent: QWidget | None = ...) -> None: ...
    def setLayout(self, layout: QLayout) -> None: ...

class QFrame(QWidget):
    class Shape(int):
        NoFrame: QFrame.Shape
        StyledPanel: QFrame.Shape

    def setFrameShape(self, shape: int) -> None: ...

class QApplication(QObject):
    def __init__(self, argv: Sequence[str]) -> None: ...
    @staticmethod
    def instance() -> QApplication | None: ...
    @staticmethod
    def processEvents() -> None: ...
    def exec(self) -> int: ...
    def setApplicationName(self, name: str) -> None: ...
    def setOrganizationName(self, name: str) -> None: ...
    def quit(self) -> None: ...

class QStatusBar(QWidget):
    def showMessage(self, text: str, timeout: int = ...) -> None: ...
    def clearMessage(self) -> None: ...
    def currentMessage(self) -> str: ...

class QMainWindow(QWidget):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def statusBar(self) -> QStatusBar: ...
    def showMaximized(self) -> None: ...

class QDialog(QWidget):
    class DialogCode:
        Accepted: int
        Rejected: int

    def setModal(self, modal: bool) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class QFileDialog(QWidget):
    @staticmethod
    def getOpenFileName(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
        filter: str = ...,
    ) -> tuple[str, str]: ...
    @staticmethod
    def getExistingDirectory(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
    ) -> str: ...
    @staticmethod
    def getSaveFileName(
        parent: QWidget | None = ...,
        caption: str = ...,
        directory: str = ...,
        filter: str = ...,
    ) -> tuple[str, str]: ...

class QDialogButtonBox(QWidget):
    class StandardButton(int):
        Ok: QDialogButtonBox.StandardButton
        Cancel: QDialogButtonBox.StandardButton

    accepted: Signal
    rejected: Signal

    def __init__(
        self, buttons: int = ..., orientation: int = ..., parent: QWidget | None = ...
    ) -> None: ...
    def addButton(self, button: QPushButton, role: int) -> None: ...
    def button(
        self, standard: QDialogButtonBox.StandardButton
    ) -> QPushButton | None: ...

class QLabel(QWidget):
    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def setWordWrap(self, wrap: bool) -> None: ...
    def setAlignment(self, alignment: int) -> None: ...
    def setStyleSheet(self, style: str) -> None: ...
    def setPixmap(self, pixmap: QPixmap) -> None: ...
    def clear(self) -> None: ...

class QLineEdit(QWidget):
    textChanged: Signal

    def setPlaceholderText(self, text: str) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def clear(self) -> None: ...
    def setReadOnly(self, enable: bool) -> None: ...

class QPlainTextEdit(QWidget):
    textChanged: Signal

    class LineWrapMode(int):
        NoWrap: QPlainTextEdit.LineWrapMode

    def setPlaceholderText(self, text: str) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def setTabChangesFocus(self, enabled: bool) -> None: ...
    def setReadOnly(self, enabled: bool) -> None: ...
    def setLineWrapMode(self, mode: int) -> None: ...
    def clear(self) -> None: ...
    def appendPlainText(self, text: str) -> None: ...
    def verticalScrollBar(self) -> QScrollBar: ...

class QComboBox(QWidget):
    class InsertPolicy:
        NoInsert: int

    currentIndexChanged: Signal

    def addItem(self, text: str, userData: object = ...) -> None: ...
    def addItems(self, texts: Iterable[str]) -> None: ...
    def blockSignals(self, block: bool) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentData(self, role: int = ...) -> object: ...
    def findData(self, data: object) -> int: ...
    def findText(self, text: str) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def currentIndex(self) -> int: ...
    def setEditable(self, editable: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setInsertPolicy(self, policy: int) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setCurrentText(self, text: str) -> None: ...
    def currentText(self) -> str: ...
    def setEditText(self, text: str) -> None: ...

class QCheckBox(QWidget):
    stateChanged: Signal

    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QTableWidgetItem:
    def __init__(self, text: str = ..., type: int = ...) -> None: ...
    def data(self, role: int = ...) -> object: ...
    def setData(self, role: int, value: object) -> None: ...
    def setText(self, text: str) -> None: ...

class QListWidgetItem:
    def __init__(self, text: str = ..., type: int = ...) -> None: ...
    def setText(self, text: str) -> None: ...
    def setData(self, role: int, value: object) -> None: ...
    def data(self, role: int) -> object: ...
    def setFlags(self, flags: int) -> None: ...
    def flags(self) -> int: ...
    def setCheckState(self, state: int) -> None: ...

class QListWidget(QAbstractItemView):
    itemSelectionChanged: Signal

    def setAlternatingRowColors(self, enable: bool) -> None: ...
    def setSelectionMode(self, mode: int) -> None: ...
    def addItem(self, item: QListWidgetItem | str) -> None: ...
    def item(self, row: int) -> QListWidgetItem | None: ...
    def selectedItems(self) -> list[QListWidgetItem]: ...
    def setCurrentItem(self, item: QListWidgetItem) -> None: ...
    def count(self) -> int: ...

class QHeaderView(QWidget):
    def setStretchLastSection(self, stretch: bool) -> None: ...

class QTableWidget(QWidget):
    def __init__(
        self, rows: int = ..., columns: int = ..., parent: QWidget | None = ...
    ) -> None: ...
    def setRowCount(self, rows: int) -> None: ...
    def setColumnCount(self, columns: int) -> None: ...
    def setHorizontalHeaderLabels(self, labels: Sequence[str]) -> None: ...
    def item(self, row: int, column: int) -> QTableWidgetItem | None: ...
    def setItem(self, row: int, column: int, item: QTableWidgetItem) -> None: ...
    def horizontalHeader(self) -> QHeaderView: ...
    def setEditTriggers(self, triggers: int) -> None: ...
    def setSelectionBehavior(self, behavior: int) -> None: ...
    def setSelectionMode(self, mode: int) -> None: ...
    def resizeRowsToContents(self) -> None: ...

class QSpinBox(QWidget):
    valueChanged: Signal

    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setSpecialValueText(self, text: str) -> None: ...
    def setSuffix(self, suffix: str) -> None: ...
    def value(self) -> int: ...
    def setValue(self, value: int) -> None: ...

class QDoubleSpinBox(QWidget):
    valueChanged: Signal

    def setRange(self, minimum: float, maximum: float) -> None: ...
    def setDecimals(self, decimals: int) -> None: ...
    def setSingleStep(self, step: float) -> None: ...
    def setSuffix(self, suffix: str) -> None: ...
    def value(self) -> float: ...
    def setValue(self, value: float) -> None: ...
    def setSpecialValueText(self, text: str) -> None: ...

class QPushButton(QWidget):
    clicked: Signal

    def __init__(self, text: str = ..., parent: QWidget | None = ...) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def setText(self, text: str) -> None: ...
    def setAutoDefault(self, enabled: bool) -> None: ...
    def setDefault(self, enabled: bool = ...) -> None: ...

class QSplitter(QWidget):
    def __init__(self, orientation: int, parent: QWidget | None = ...) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def setStretchFactor(self, index: int, stretch: int) -> None: ...

class QGraphicsScene(QObject):
    def __init__(self, parent: QObject | None = ...) -> None: ...
    def clear(self) -> None: ...
    def addItem(self, item: object) -> None: ...
    @overload
    def setSceneRect(self, rect: object) -> None: ...
    @overload
    def setSceneRect(self, x: float, y: float, width: float, height: float) -> None: ...
    def sceneRect(self) -> object: ...
    def items(self) -> list[object]: ...

class QGraphicsView(QWidget):
    def setScene(self, scene: QGraphicsScene) -> None: ...
    def renderHints(self) -> int: ...
    def setRenderHints(self, hints: int) -> None: ...
    def resetTransform(self) -> None: ...
    def scale(self, sx: float, sy: float) -> None: ...
    def fitInView(self, target: object, mode: int | None = ...) -> None: ...
    def sceneRect(self) -> object: ...

class QSlider(QWidget):
    class Orientation(int):
        Horizontal: int
        Vertical: int

    valueChanged: Signal

    def __init__(self, orientation: int, parent: QWidget | None = ...) -> None: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...

class QStackedWidget(QWidget):
    def addWidget(self, widget: QWidget) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...
    def renderHints(self) -> int: ...
    def setRenderHints(self, hints: int) -> None: ...

class QScrollArea(QWidget):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def setWidget(self, widget: QWidget) -> None: ...
    def setWidgetResizable(self, resizable: bool) -> None: ...

class QAbstractItemView(QWidget):
    class SelectionMode:
        SingleSelection: int
        NoSelection: int

    class SelectionBehavior:
        SelectRows: int

    class EditTrigger:
        NoEditTriggers: int

class QTreeWidget(QAbstractItemView):
    itemSelectionChanged: Signal
    customContextMenuRequested: Signal

    def setRootIsDecorated(self, decorated: bool) -> None: ...
    def setAlternatingRowColors(self, enable: bool) -> None: ...
    def setHeaderLabels(self, labels: Sequence[str]) -> None: ...
    def setSelectionMode(self, mode: int) -> None: ...
    def setSelectionBehavior(self, behavior: int) -> None: ...
    def addTopLevelItem(self, item: QTreeWidgetItem) -> None: ...
    def clear(self) -> None: ...
    def columnCount(self) -> int: ...
    def resizeColumnToContents(self, column: int) -> None: ...
    def selectedItems(self) -> list[QTreeWidgetItem]: ...
    def itemAt(self, point: QPoint) -> QTreeWidgetItem | None: ...
    def setCurrentItem(self, item: QTreeWidgetItem) -> None: ...
    def topLevelItemCount(self) -> int: ...
    def topLevelItem(self, index: int) -> QTreeWidgetItem | None: ...
    def viewport(self) -> QWidget: ...

class QTreeWidgetItem:
    @overload
    def __init__(self, parent: QTreeWidget | None = ..., type: int = ...) -> None: ...
    @overload
    def __init__(self, strings: Iterable[str], type: int = ...) -> None: ...
    @overload
    def __init__(
        self, parent: QTreeWidget, strings: Iterable[str], type: int = ...
    ) -> None: ...
    def setText(self, column: int, text: str) -> None: ...
    def text(self, column: int) -> str: ...
    def setData(self, column: int, role: int, value: object) -> None: ...
    def data(self, column: int, role: int) -> object: ...

class QTabWidget(QWidget):
    currentChanged: Signal

    def setDocumentMode(self, enabled: bool) -> None: ...
    def addTab(self, widget: QWidget, label: str) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...

class QMenu(QWidget):
    def addAction(self, text: str) -> QAction: ...
    def addSeparator(self) -> QAction: ...
    def exec(self, pos: QPoint | None = ...) -> QAction | None: ...

class QMessageBox:
    class StandardButton(int):
        Ok: QMessageBox.StandardButton
        Cancel: QMessageBox.StandardButton
        Yes: QMessageBox.StandardButton
        No: QMessageBox.StandardButton

    @staticmethod
    def information(
        parent: QWidget | None, title: str, text: str
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def warning(
        parent: QWidget | None, title: str, text: str
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def critical(
        parent: QWidget | None, title: str, text: str
    ) -> QMessageBox.StandardButton: ...
    @staticmethod
    def question(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: int = ...,
        defaultButton: int = ...,
    ) -> QMessageBox.StandardButton: ...

class QInputDialog:
    @staticmethod
    def getText(
        parent: QWidget | None,
        title: str,
        label: str,
        mode: int = ...,
        text: str = ...,
    ) -> tuple[str, bool]: ...

class QScrollBar(QWidget):
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def maximum(self) -> int: ...
