from collections.abc import Mapping

DEFAULT_PERSONA_PROMPT: str

class PersonaPromptError(ValueError): ...

def format_persona_question(
    persona_id: str,
    template: str = ...,
) -> str: ...
def extract_answer_text(response: Mapping[str, object]) -> str: ...
def extract_tags(response: Mapping[str, object]) -> tuple[str, ...]: ...
def extract_highlights(response: Mapping[str, object]) -> tuple[str, ...]: ...
def score_from_answer(answer: str) -> float: ...
def source_from_response(response: Mapping[str, object]) -> str: ...
def synopsis_from_answer(answer: str) -> str | None: ...
