from collections.abc import Callable, Mapping, Sequence
from typing import Any, Self

class Element:
    value: Any
    rows: Any
    label: str
    border_title: str
    cursor_type: str

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: object | None,
    ) -> None: ...
    def classes(self, value: str) -> Self: ...
    def props(self, value: str) -> Self: ...
    def set_content(self, content: str) -> None: ...
    def clear(self) -> None: ...
    def push(self, message: str) -> None: ...
    def disable(self) -> None: ...
    def enable(self) -> None: ...
    def on_click(self, handler: Callable[..., Any]) -> None: ...

class Table(Element):
    rows: Any

class Log(Element):
    def push(self, message: str) -> None: ...
    def clear(self) -> None: ...

class Button(Element):
    disabled: bool
    def disable(self) -> None: ...
    def enable(self) -> None: ...

class Input(Element):
    placeholder: str
    def disable(self) -> None: ...
    def enable(self) -> None: ...

class Checkbox(Element):
    value: bool

class Number(Element):
    value: float | int | None

class Selector(Element):
    value: Any

class Column(Element): ...
class Expansion(Element): ...
class Markdown(Element): ...
class Label(Element): ...
class Separator(Element): ...

class _UiModule:
    def markdown(self, content: str) -> Markdown: ...
    def table(
        self,
        *,
        columns: Sequence[Mapping[str, object]],
        rows: Sequence[Mapping[str, object]],
        row_key: str | None = ...,
    ) -> Table: ...
    def column(self) -> Column: ...
    def input(
        self, label: str | None = ..., placeholder: str | None = ...
    ) -> Input: ...
    def button(
        self,
        label: str,
        *,
        on_click: Callable[..., Any] | None = ...,
        id: str | None = ...,
    ) -> Button: ...
    def checkbox(self, label: str, value: bool = ...) -> Checkbox: ...
    def number(
        self,
        label: str | None = ...,
        value: float | None = ...,
        min: float | None = ...,
        max: float | None = ...,
        step: float | None = ...,
    ) -> Number: ...
    def log(self) -> Log: ...
    def label(self, text: str) -> Label: ...
    def expansion(self, title: str, *, value: bool | None = ...) -> Expansion: ...
    def select(
        self, options: Sequence[str] | Mapping[str, object], *, label: str | None = ...
    ) -> Selector: ...
    def separator(self) -> Separator: ...
    def run(
        self,
        *,
        host: str = ...,
        port: int = ...,
        native: bool | None = ...,
        reload: bool | None = ...,
    ) -> None: ...

ui: _UiModule
