class VideoCapture:
    def __init__(self, source: int | str) -> None: ...
    def read(self) -> tuple[bool, object]: ...
    def isOpened(self) -> bool: ...

def imread(path: str) -> object | None: ...
