def ticks_ms() -> int: ...
def ticks_add(value: int, delta: int) -> int: ...
def ticks_diff(a: int, b: int) -> int: ...
def sleep_ms(ms: int) -> None: ...
def sleep(seconds: float) -> None: ...
def time() -> float: ...
