
STA_IF: int

class WLAN:
    def __init__(self, interface_id: int) -> None: ...
    def active(self, is_active: bool | None = ...) -> bool: ...
    def isconnected(self) -> bool: ...
    def connect(self, ssid: str, password: str) -> None: ...
